force-app/main/default/objects/Litify_Case__c/Litify_Case__c.object-meta.xml
<CustomObject>
    <label>Litify Case</label>
    <nameField>
        <label>Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Litify Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Litify_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <displayFormat>LC-{0000}</displayFormat>
    <label>Case Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/LWCCaseMemberHierarchyController.cls
public with sharing class LWCCaseMemberHierarchyController {
    @AuraEnabled
    public static List<Litify_Case__c> getAllLitifyCases() {
        List<Litify_Case__c> litifyCases = [
            SELECT 
                Id,
                Name,
                Case_Number__c
            FROM
                Litify_Case__c
        ];

        System.debug('>>> litifyCases: ' + litifyCases);
        return litifyCases;
    }
}